apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-react-app
  template:
    metadata:
      labels:
        app: vite-react-app
    spec:
      containers:
      - name: vite-react-app
        image: jsdarshan/snipify:latest
        ports:
        - containerPort: 3000
